# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fish Properties
minecraft_version=1.6.4-MITE
yarn_mappings=1.6.4
loader_version=0.15.0

# Mod Properties
mod_version=1.0.2
mod_id=extreme-forging-additions
mod_name=Extreme Forging Additions
archives_base_name=extreme-forging-additions

# Maven Properties
maven_group=org.moddedmite
maven_id=extreme-forging-additions

fabric_version=0.91.1+1.20.4

# Run Properties
username=Dev
screen_width=854
screen_height=480
